name: SESCO Production Deployment

on:
  push:
    branches:
      - develop

env:
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
  DOCKERHUB_PW: ${{ secrets.DOCKERHUB_PW }}
  AWS_SSM_ACCESS_KEY: ${{ secrets.AWS_SSM_ACCESS_KEY }}
  AWS_SSM_SECRET_KEY: ${{ secrets.AWS_SSM_SECRET_KEY }}
  IMAGE_TAG: ${{ github.sha }}

jobs:  
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USER }}
        password: ${{ env.DOCKERHUB_PW }}

    - name: build and release to DockerHub
      env:
        NAME: ${{ env.DOCKERHUB_USER }}
        REPO: sesco-server
      run: |
        docker build -t $REPO .
        docker tag $REPO:latest $NAME/$REPO:latest
        docker push $NAME/$REPO:latest

    - name: Configure AWS credentials for SSM
      uses: aws-actions/configure-aws-credentials@v1 
      with:
        aws-access-key-id: ${{ env.AWS_SSM_ACCESS_KEY }}
        aws-secret-access-key: ${{ env.AWS_SSM_SECRET_KEY }}
        aws-region: ap-northeast-2

    - name: AWS SSM Send-Deploy-Command
      run: |
        aws ssm send-command --targets Key=tag:Name,Values=sesco-server --document-name SESCO-SERVER-EC2-Reload
